<?php

namespace Tests\Modules\Dosen\Service;

use App\Models\DosenData;
use App\Models\User;
use App\Modules\Dosen\Entity\Dosen;
use App\Modules\Dosen\Service\DosenService;
use App\Modules\Pengguna\Service\PenggunaService;
use App\Providers\AppServiceProvider;
use PHPUnit\Framework\TestCase;
use Tests\Modules\Pengguna\Service\PenggunaServiceTest;

class DosenServiceTest extends TestCase
{
    public function  setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        DosenService::$pm = new DosenData();
        PenggunaService::$pm = new User();
    }

    public function testDelete()
    {

    }

    public function testInsert(){
        $nama = "Test Dosen";
        $password = "12345678";
        $nomorInduk = "2099002";
        $email = "dosen@test.com";
        $tanggalLahir = "10/16/2003";
        $tempatLahir= "Bali";
        $jenisKelamin ="L";
        $alamat ="Dipatiukur";
        $notelepon ="086537956";
        $jabatan ="Dosen";
        $programstudi = "Informatika";
        $bidangIlmu = 'Teknologi';
        $gelarAkademik = "Master";
        $stausIkatanKerja = "Honorer";
        $statusDosen = true;

        $res = DosenService::insert($nama,$password,  $nomorInduk, $email, $tanggalLahir, $tempatLahir,
                            $jenisKelamin, $alamat,$notelepon, $jabatan,$jabatan,$programstudi,$bidangIlmu,
                            $gelarAkademik, $stausIkatanKerja,$statusDosen );
        self::assertEquals(true,$res);
    }

    public function testGetAll()
    {

    }

    public function testUpdate()
    {

    }

    public function testUserInfo()
    {

    }
}
