<?php

namespace Tests\Modules\Pengguna\Service;

use App\Models\User;
use App\Modules\Pengguna\Persistence\PenggunaPersistence;
use App\Modules\Pengguna\Service\PenggunaService;
use phpDocumentor\Reflection\Types\Self_;
use Tests\TestCase;

class PenggunaServiceTest extends TestCase
{
    protected function setUp(): void {
        parent::setUp(); // TODO: Change the autogenerated stub
        PenggunaService::$pm =new User();
    }

    public function testDelete() {

    }

    public function testResetPassword()
    {

    }

    public function testLogin()
    {
        $email = "newUser@gmail.com";
        $password = "12345678";

        $this->assertEquals(true,PenggunaService::login($email,$password));
    }

    public function testUpdate()
    {

    }

    public function testTestService()
    {

    }

    public function testGantiPassword()
    {

    }

    public function testGetAll()
    {

    }

    public function testInsert()
    {

    }

    public function testUserInfo()
    {

    }
}
